@@ .. @@
 import React from "react";
-import { AIModelsSection } from "./sections/AIModelsSection/AIModelsSection";
-import { CallToActionSection } from "./sections/CallToActionSection/CallToActionSection";
-import { FeaturesSection } from "./sections/FeaturesSection/FeaturesSection";
-import { MainContentSection } from "./sections/MainContentSection/MainContentSection";
-import { ProjectsGallerySection } from "./sections/ProjectsGallerySection/ProjectsGallerySection";
-import { TestimonialsSection } from "./sections/TestimonialsSection/TestimonialsSection";
-import { UserProfileSection } from "./sections/UserProfileSection";
-import { VideoCreationSection } from "./sections/VideoCreationSection/VideoCreationSection";
-import { VideoShowcaseSection } from "./sections/VideoShowcaseSection/VideoShowcaseSection";
+import { AIModelsSection } from "./sections/AIModelsSection/AIModelsSection";
+import { CallToActionSection } from "./sections/CallToActionSection/CallToActionSection";
+import { FeaturesSection } from "./sections/FeaturesSection/FeaturesSection";
+import { MainContentSection } from "./sections/MainContentSection/MainContentSection";
+import { ProjectsGallerySection } from "./sections/ProjectsGallerySection/ProjectsGallerySection";
+import { TestimonialsSection } from "./sections/TestimonialsSection/TestimonialsSection";
+import { UserProfileSection } from "./sections/UserProfileSection";
+import { VideoCreationSection } from "./sections/VideoCreationSection/VideoCreationSection";
+import { VideoShowcaseSection } from "./sections/VideoShowcaseSection/VideoShowcaseSection";